### ISSUE TITLE
telescopic Clamp-o-tron docking module issue

### ISSUE THREAD

**Issue by Thorimus** [ChrisAdderley/StationPartsExpansionRedux#101]
The port will not dock to another port if it is deployed, but works fine when not deployed. It behaves the same when trying to dock to a stock docking port.

**Comment by ChrisAdderley** [comment]
Are you using the latest version (ie, as of https://github.com/ChrisAdderley/StationPartsExpansionRedux/commit/1a0d1c5b8cab609fdd503c761a4a3d96dfda02fe, about 20 hours ago)? This bug was reported and fixed in that commit.

**Comment by Thorimus** [comment]
@ChrisAdderley I was using the latest version as of when my bug report was made, however the save was created and involved crafts launched in an earlier version, which might be contributing to the issue. (update was installed by completely removing old version first) I will give it a test with the latest version with two "fresh" spacecraft when I can.

**Comment by ChrisAdderley** [comment]
Should actually be fixed now
