### ISSUE TITLE
Kerbal Position Adjustments

### ISSUE THREAD

**Issue by ChrisAdderley** [ChrisAdderley/StationPartsExpansionRedux#108]
Verify and adjust the kerbal positions on the following parts:

- [x] 3.75m centrifuge
- [x] 3.75m compact centrifuge
- [x] 3.75m aquaculture module
- [x] 2.5m centrifuge
- [x] 1.25m large inflatable hab
- [ ] 1.25m inflatable compact hab
- [ ] 1.25m inflatable compact hab (2)

**Comment by lOmicronl** [comment]
Unsure if it qualifies under this header, but:

If I take the PPD-8 "Wharf" Station Core and put it on the launchpad, one of the three Kerbals' personal IVA view will show as the underside of the launchpad instead of the inside of the PPD-8.

**Comment by ChrisAdderley** [comment]
Yep this is the place. Good find, transform got... moved somehow.
