### ISSUE TITLE
Loading/timewarp can have bad effects on base frames

### ISSUE THREAD

**Issue by ChrisAdderley** [ChrisAdderley/StationPartsExpansionRedux#114]
See here: https://forum.kerbalspaceprogram.com/index.php?/topic/170211-131-stockalike-station-parts-redux-january-28th/&do=findComment&comment=3280809

**Comment by ChrisAdderley** [comment]
Believe I have solved this but I can't test every edge case.

**Comment by Brusura** [comment]
Can I help with the testing?

**Comment by ChrisAdderley** [comment]
You can pull the dev branch, I believe it is compiled there.

**Comment by ChrisAdderley** [comment]
Anyone had a chance to test this in 1.0.2?

**Comment by Brusura** [comment]
Tested it in my setup, I do not see anymore noticeable effect on load/warp

**Comment by ChrisAdderley** [comment]
Sweet, thanks for the verification
