### ISSUE TITLE
PXL-E Mercury IVA misalignment

### ISSUE THREAD

**Issue by f-d** [ChrisAdderley/StationPartsExpansionRedux#119]
IVA orientation/alignment and rotation direct remains consistent with orientation of part when initially placed into VAB/SPH.

For example, placement of the centrifuge in the SPH, then head-over-tail rotation leads to the centrifuge itself rotating clockwise when viewed from the tail, but the IVA (floating windows and all) rotating anticlockwise. The part can be deployed or retracted when placed - the issue still occurs.

Placement of the part in the "correct" orientation attached to a vessel, then the use of the rotation tool on a part closer to the root of the vessel (including the root itself), or picking up and rotating the root part seems to not result in the same issue.

**Comment by ChrisAdderley** [comment]
There is an consistent inconsistency in the way that Squad designed the IVA layout which makes this a hideous problem. I know what it is now but not yet how to fix it.
