### ISSUE TITLE
SSPXR-CLS.cfg Missing sspx-lab-375-1 in definitions

### ISSUE THREAD

**Issue by Oobbok** [ChrisAdderley/StationPartsExpansionRedux#123]
Could not find the PXL-2 'FATE' Deep-Space Laboratory Module in SSPXR-CLS.cfg for CLS.

@PART[sspx-lab-375-1]:HAS[!MODULE[ModuleConnectedLivingSpace]]:NEEDS[ConnectedLivingSpace]
{
  MODULE
  {
    name = ModuleConnectedLivingSpace
    passable = true
  }
}

P.S. Love the mod. So much fun.

**Comment by ChrisAdderley** [comment]
Was already resolved in https://github.com/ChrisAdderley/StationPartsExpansionRedux/pull/117
