### ISSUE TITLE
Not localized CrewSkillNeeded

### ISSUE THREAD

**Issue by alxbou** [ChrisAdderley/StationPartsExpansionRedux#124]
In the localized version of the game, property ExperienceTrait.TypeName is also localized. Therefore, in the configuration of parts, the CrewSkillNeeded parameter must be localized.

		CrewSkillNeeded = #autoLOC_500103 // instead of "Engineer"

- [ ] Parts\Extendable\extendable-125\sspx-inflatable-centrifuge-125-1.cfg
- [ ] Parts\Extendable\extendable-125\sspx-inflatable-centrifuge-125-2.cfg
- [ ] Parts\Extendable\extendable-125\sspx-inflatable-hab-125-1.cfg
- [ ] Parts\Extendable\extendable-125\sspx-inflatable-hab-125-2.cfg
- [ ] Parts\Extendable\extendable-125\sspx-inflatable-hab-125-3.cfg
- [ ] Parts\Extendable\extendable-25\sspx-inflatable-centrifuge-25-1.cfg
- [ ] Parts\Extendable\extendable-25\sspx-inflatable-hab-25-1.cfg
- [ ] Parts\Extendable\extendable-25\sspx-inflatable-hab-25-2.cfg
- [ ] Parts\Extendable\extendable-375\sspx-expandable-centrifuge-375-1.cfg
- [ ] Parts\Extendable\extendable-375\sspx-expandable-centrifuge-375-2.cfg

**Comment by ChrisAdderley** [comment]
It's be better to actually figure out if there is an unlocalized variable, which there should be.
