### ISSUE TITLE
PPD-EVAC-U-8 Service Airlock has a permanently obstructed hatch

### ISSUE THREAD

**Issue by Mihara** [ChrisAdderley/StationPartsExpansionRedux#125]
I'm assuming you would prefer the bug reports here instead of the forum thread, am I correct?

Anyway, it's all in the title: Launching a bare airlock part with a kerbal in it I am unable to get the kerbal to exit.

**Comment by ChrisAdderley** [comment]
Yes, here is better.

**Comment by Mihara** [comment]
Can no longer replicate in 1.0.1, thank you!
