### ISSUE TITLE
Crewed modules with no hatch are used in "save Kerman from X"-contracts

### ISSUE THREAD

**Issue by marcusirgens** [ChrisAdderley/StationPartsExpansionRedux#128]
There's a random chance for rescue contracts in career mode to use one of the SSPXr modules with no hatch, making it impossible to rescue the poor souls before you unlock the grabby parts.

**Comment by theonegalen** [comment]
This is a stock issue. Use the Rescue Pod Validator mod to fix it:

https://forum.kerbalspaceprogram.com/index.php?/topic/141560-131-ksp-rescue-pod-validator-no-more-kerbals-spawning-in-inflatable-modules/

**Comment by ChrisAdderley** [comment]
Indeed, can't be helped by me. That mod is what you want.

**Comment by marcusirgens** [comment]
May I suggest that you move this mod into the reccommended addons list? :) Thanks for your quick response.

**Comment by ChrisAdderley** [comment]
Good idea :)
