### ISSUE TITLE
TAC LS values are wildly off

### ISSUE THREAD

**Issue by henrybauer** [ChrisAdderley/StationPartsExpansionRedux#129]
PXL-CRG-1 Logistics Module, set to "Life Support"
9.280 t full
63,161 L according to KIS

571.3 Food (3y 287d)
37.8 Water (159 d)
57831.9 Oxygen (3y 287d)
480.9 Waste (33y 406d)
52.0 WasteWater (171d)
49954.4 CarbonDioxide (3y 287d)

Just looking at this container alone, only Food, Oxygen and CarbonDioxide give similar lifetimes.  The values for Waste seem wildly high - 10 times the other values.  Water and WasteWater are quite low compared to Food.

However, when compared to the stock TAC containers, they're even worse:

Life Support Supplies Container, 2.5m plus Life Support Waste Container, 2.5m
2.6 t full
6,182 L according to KIS

1038.3 Food (6y 286d)
686.3 Water (6y 286d)
105113.2 Oxygen (6y 286d)
179.2 Waste (12y 280d)
1658.8 WasteWater (12y 281d)
172334.5 CarbonDioxide (12y 279d)

The PXL-CRG-1 is 3.5 times the mass, and 10.2 times the volume, but has half the supplies!

Through some messy Excel magic and trial and error, this is what I think the values should be, to more closely match the stock TAC containers:

		name = Food
		unitsPerVolume = 0.115364097

		name = Water
		unitsPerVolume = 0.076252751

		name = Oxygen
		unitsPerVolume = 11.67884096

		name = Waste
		unitsPerVolume = 0.019914052

		name = WasteWater
		unitsPerVolume = 0.184336663

		name = CarbonDioxide
		unitsPerVolume =  19.15107727

This gives 25y 2d for Food/Water/Oxygen, and 47y 194d for Waste/WasteWater/CarbonDioxide for the PXL-CRG-1.  Basically the PXL-CRG-1 is about the same size on screen as two and a half 3.75m LS plus two and a half 3.75m Waste containers, so I adjusted values to match.  Super-scientific.

For more precision, TAC has a spreadsheet with all its math here: https://github.com/KSP-RO/TacLifeSupport/wiki/FAQ

I couldn't find "unit/L" calculations on their spreadsheet.  However one notable thing from the spreadsheet is that they appear to store Oxygen and CarbonDioxide compressed (liquefied even) which explains the high density they get on the stock containers.

**Comment by ChrisAdderley** [comment]
Might want to chime in to the conversation by people who use that mod (All the compatibility patches are user-contributed): https://forum.kerbalspaceprogram.com/index.php?/topic/170211-131-stockalike-station-parts-redux-january-28th/&do=findComment&comment=3291099

**Comment by henrybauer** [comment]
majNUN's patch isn't actually in the game yet, and I thought it was.  My mistake.  majNUN's patch solves everything.
