### ISSUE TITLE
Switching cargoes exerts destructive force on Log Modules and Containers

### ISSUE THREAD

**Issue by GHrynk** [ChrisAdderley/StationPartsExpansionRedux#133]
When switching cargo types on the pad or in orbit (after cheat to height), there is a force - perhaps due to the sudden change in mass - that imposes an extreme rotational movement on the vessel.  When on the pad, this tosses the vessel into the air, sometimes immediately destroying the container or objects underneath it, that are against the ground.  In orbit, the vessel goes into a wild spin.  I've tried this with the PPD-CRG-2, PPD-CRG-3 and KRDA-T400.  Using KSP 1.3.1 x64 with SSPXr 1.0.2.

**Comment by ChrisAdderley** [comment]
Bug with B9Partswitch, workaround added for next version
