### ISSUE TITLE
B-EX extendable crew tubes mis-aligned for 'control form here'

### ISSUE THREAD

**Issue by Rodg88** [ChrisAdderley/StationPartsExpansionRedux#137]
When you select the 'control from here' option on the B-EX 1 or 2, the forward direction is set 90 degrees off the forward direction of the grabbing end.
Eg:
https://i.imgur.com/0E2HCYL.png

Possibly due to the initial orientation of the parts when placed in the editor (they start out 'sideways')

**Comment by ChrisAdderley** [comment]
I'll uh, investigate.

**Comment by ChrisAdderley** [comment]
Fixed for next version

**Comment by ChrisAdderley** [comment]
Fixed in latest version.

**Comment by Cypris2010** [comment]
I know this ist old, but I can't set the part as a target.
