### ISSUE TITLE
1.25m Docking Port (dockingPort2) generates Exceptions with Ven's SR installed

### ISSUE THREAD

**Issue by Poodmund** [ChrisAdderley/StationPartsExpansionRedux#150]
It seems that when you have SSPXr installed alongside the 1.4.* branch of Ven's Stock Revamp (https://github.com/Kerbas-ad-astra/Stock-Revamp/tree/KSP_1.4 ) exceptions are thrown when you select the docking port part in the editor. SSPXr's 1.25m Docking Port is loaded/patched in after Ven's and so that is the model that is loaded into the editor, however, I think there may be some residual part modules from the Ven's part config that are loaded before yours that remain, as when you select the 1.25m Docking Port in the editor a bunch of Exceptions are thrown; mainly to do with drag cubes.

Here is the output log of a session where I just go into the Editor, pick a 1.25m Docking Port part, delete it, pick a 2.5m Docking Port part, delete it, pick a 1.25m Docking Port part, delete it, then quit out the game. This is on a Vanilla 1.4.5 install with SSPXr, its dependencies and the 1.4.* branch of Ven's Stock Revamp: https://www.dropbox.com/s/chm7x145hhlutdj/output_log.txt?dl=0

I can just delete the docking port part out of Vens and all references to it and it fixes the issue but seeing as how both a popular mods, I thought there may be the possibility that you'd want to patch your part in such a way that it stops Ven's one from screwing yours up... (?)

For reference, Ven's dockingPort2 config entry can be found at GameData/VenStockRevamp/Squad/Data/Utility.cfg starting at Line 344.

**Comment by Kerbas-ad-astra** [comment]
It would also help to see the dockingPort2 entry from Module Manager's cache; there may be an issue with animation name references or something getting mismatched between the two mods.

**Comment by Kerbas-ad-astra** [comment]
After some testing, the problem was that VSR adds an animation module, while SSPX's model has no animations.  Easy enough to add a little more 'cleanup' to the patch.

**Comment by ChrisAdderley** [comment]
Resolved by 99d2dc4, will be in next release.
