### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by SergiRuizZarzuelo** [ChrisAdderley/StationPartsExpansionRedux#156]
Hi:
I'm just starting to translate the mod into spanish. How can I upload the file when I'll finish it?

**Comment by ChrisAdderley** [comment]
Make a Github pull request - it's the easiest for me. If you're not familiar with GitHub, you can upload it to pastebin or similar and post here - I can integrate it.

**Comment by SergiRuizZarzuelo** [comment]
Ok.
Thanks

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by SergiRuizZarzuelo** [comment]
Done!!

**Comment by SergiRuizZarzuelo** [comment]
If need more translations…..

**Comment by SergiRuizZarzuelo** [comment]
Also uploaded the B9Part Switch localization file es-es

**Comment by SergiRuizZarzuelo** [comment]
Pull Request Opened...

**Comment by ChrisAdderley** [comment]
Was added in last release

**Comment by SergiRuizZarzuelo** [comment]
Thanks!
________________________________
De: Chris Adderley <notifications@github.com>
Enviado: miércoles, 10 de octubre de 2018 21:29
Para: ChrisAdderley/StationPartsExpansionRedux
Cc: SergiRuizZarzuelo; Author
Asunto: Re: [ChrisAdderley/StationPartsExpansionRedux] Spanish Translation (#156)


Was added in last release
