### ISSUE TITLE
Clamp-O-Tron and Telescopic Docking Module Orientation Indicators

### ISSUE THREAD

**Issue by GHrynk** [ChrisAdderley/StationPartsExpansionRedux#163]
Requesting indicators/markings for orientation of SSPXr reskinned Clamp-O-Tron docking ports and new Telescoping Clamp-O-Tron Docking Port.  Ref forum post https://forum.kerbalspaceprogram.com/index.php?/topic/170211-145-stockalike-station-parts-redux-sept-30/&do=findComment&comment=3469433

**Comment by ChrisAdderley** [comment]
I have changed the replacement port to be consistent with the original port in terms of the orientation of surface features. In addition I've done the same with the extendable port. This is all I will scope for this ticket at this time. 

It does occur to me that viewing the model, the extensible port has specific colored docking lights arranged to indicate up direction.
