### ISSUE TITLE
IndicatorLight compatibility restoration on reskinned Clamp-O-Tron

### ISSUE THREAD

**Issue by GHrynk** [ChrisAdderley/StationPartsExpansionRedux#164]
Requesting restoration or IndicatorLights Community Extensions patch for LED light functionality on re-skinned Clamp-O-Tron docking ports.  Ref forum post https://forum.kerbalspaceprogram.com/index.php?/topic/170211-145-stockalike-station-parts-redux-sept-30/&do=findComment&comment=3469433

**Comment by ChrisAdderley** [comment]
Fix implemented, in next version
