### ISSUE TITLE
MKS Patch Enhancement

### ISSUE THREAD

**Issue by PolecatEZ** [ChrisAdderley/StationPartsExpansionRedux#165]
Changelog in the notes at the top.

I'll spend an extra day on it to get a few more things in, as well as a balance pass once I do some play testing in the morning.

Another forum user wanted a fix for the material kits by containers, and that's in one file.  The other has my initial additions to make everything MKS compatible.

[SSPXR-USILogistics.zip](https://github.com/ChrisAdderley/StationPartsExpansionRedux/files/2490698/SSPXR-USILogistics.zip)

Curious thing...is the PPD-24 Itinerant Service Module a part of this pack?  I couldn't find it anywhere.

**Comment by PolecatEZ** [comment]
[SSPXR-MKS Updates.zip](https://github.com/ChrisAdderley/StationPartsExpansionRedux/files/2494610/SSPXR-MKS.Updates.zip)

I'm declaring this "close enough for government work" and "if I ever make another hacked together part, shoot me."  Spent all day hacking 2 different parts together and just couldn't get a nice result, but its usable at least.

Patch notes are in the zip.

**Comment by ChrisAdderley** [comment]
I believe this is now covered in the latest release.
