### ISSUE TITLE
Some Containers missing Chemicals from their list of tweakables

### ISSUE THREAD

**Issue by PolecatEZ** [ChrisAdderley/StationPartsExpansionRedux#166]
Unless I'm just blind.  This is something that shook out during the MKS patch testing.  Not sure if Chemicals are used by other mods though, so maybe something that needs added to the MKS patch also.

n/t

**Comment by ChrisAdderley** [comment]
Which containers, and which tank types should have it? 

A quick browse indicates that 
1. I don't see any tank definitions for it at all
2. I didn't even make an icon for it so....

Should it be its own container type or in something else?

**Comment by ChrisAdderley** [comment]
Going to assume this is unneeded then.
