### ISSUE TITLE
Station with Harbour + Fate causes experiment null pointer exception

### ISSUE THREAD

**Issue by mister-walter** [ChrisAdderley/StationPartsExpansionRedux#167]
Creating a station that contains a Harbour module connected to a Fate module, plus any experiment part, results in a null pointer exception when the experiment is run.

I am using KSP 1.4.5 on Windows.

I have attached both a log file and a save file with such a station.
[Test.zip](https://github.com/ChrisAdderley/StationPartsExpansionRedux/files/2500192/Test.zip)
[KSP.log](https://github.com/ChrisAdderley/StationPartsExpansionRedux/files/2500193/KSP.log)

**Comment by ChrisAdderley** [comment]
I can't open either of those files unfortunately. 

Is this case only when the two are combined? A Fate lab runs an experiment ok?

**Comment by mister-walter** [comment]
Oops sorry, probably due to the GitHub problems going on right now.

[Here are the files hosted on another site.](https://drive.google.com/open?id=1zuuCDm68IyxDkZXlIm-XNs1tMHSM9bdh)

Indeed this only occurs when the two are combined. I'll grab a mod list for you ASAP, I originally noticed it when using SCANSat and DMagic Orbital Science parts, but when trying to narrow down the problem discovered that it also occurs with stock experiments.

**Comment by ChrisAdderley** [comment]
Unfortunately the logfile does not bring clarity. I will need to take some time to do tests later on. Can't see what might be going on from the configs, they are both really quite simple parts.

**Comment by mister-walter** [comment]
Thanks for looking into it! If I have time tonight I'll do more minimization work to determine if this happens without any other mods. If you think it would be helpful, I could also try setting up the appropriate Unity version and using the VS debugger to investigate further.

**Comment by mister-walter** [comment]
The issue does not occur with:

- stock lab and Harbour module
- fate lab and MK1
- fate lab and pier or wharf

**Comment by ChrisAdderley** [comment]
Ok, I can't repro this so either I fixed it as a result of fixing other things, or something's up:

Steps taken:
1. Create ship made of 1x Pressure Barometer, 1x harbour module, 1x fate module
2. Fill lab with scientists, fill harbour with others
3. Go to pad
4. Run the experiment, click process in lab

**Comment by ChrisAdderley** [comment]
Aha, I reproduced it by reverting some changes!

**Comment by mister-walter** [comment]
Thanks so much for your help!
