### ISSUE TITLE
Centrifuges' spinning EC consumption

### ISSUE THREAD

**Issue by yalov** [ChrisAdderley/StationPartsExpansionRedux#170]
Only one of the 5 Centrifuges has SpinResource and SpinResourceRate fields, other ones do not require any EC

**Comment by yalov** [comment]
@GarwelGarwel
relative to KerbalHealth Centrifuges Microgravity support

can ModuleKerbalHealth-Microgravity action and ModuleDeployableCentrifuge action be sticked together, so they start/stop with one button in the part menu?
also KerbalHealth::resourceConsumption == SSPExR::SpinResource and
multipliers depend on centrifuges max gravity

**Comment by ChrisAdderley** [comment]
Uh none of them should require anything. I'll check it out.

**Comment by ChrisAdderley** [comment]
Released.
