### ISSUE TITLE
Question/Concern with the "sspx-aquaculture-375-1" converters

### ISSUE THREAD

**Issue by FlushF00t** [ChrisAdderley/StationPartsExpansionRedux#172]
Hello,

This may be my fault for not not installing all mods that are known to Kerbal-kind, (though I did use CKAN) but I do find it strange that the "Fish Farm" (AquaCulture module) has one conversion option uses waste and ore to make "fertilizer", while the unit has "mineral" storage but no fertilizer storage (and minerals are a necessary input in some of your other greenhouses like the PXL-R4NCH large hydroponics module)... Is there a way either to convert Fertilizer back to Minerals, or can you point out which config file manages the conversion of Ore+Waste -> Fertilizer (so I can make it become Mineral instead?
![ksp-aqua](https://user-images.githubusercontent.com/45285035/48937383-e4e10200-eedb-11e8-9fcc-adcef9761771.jpg)
![ksp-r4nch](https://user-images.githubusercontent.com/45285035/48937520-5f118680-eedc-11e8-84b5-4e6688339189.jpg)
![ksp-f412m](https://user-images.githubusercontent.com/45285035/48937778-2de58600-eedd-11e8-957e-2a710ce874aa.jpg)

**Comment by ChrisAdderley** [comment]
I saw you posted this in the forums, did you get the answer you needed? Can I close this?

**Comment by FlushF00t** [comment]
Yes, it appears that by changing “Fertilizer” to Minerals in the cfg will work!

Thanks
