### ISSUE TITLE
SpecializedParts and Machinery not enabled without MKS

### ISSUE THREAD

**Issue by Critter79606** [ChrisAdderley/StationPartsExpansionRedux#173]
SpecializedParts and Machinery require MKS for the containers to be enabled.  These are also used by the Global/Ground Construction mod (GC) along with MaterialKits.  GC can be used stand alone or with MKS.
I'd like to see these resources available to either, as I try to keep stations using only this mods parts.
Also, since GC uses MaterialKits, it seems only reasonable that deployment of station parts require them like MKS.

I've already tested the changes on my system and am attaching them, but wasn't sure if the 2 resources should just rely on CommunityResourcePack at the top like the MaterialKits do, or if I should have and/or-ed the GroundConstruction to the MKS to restrict it.  
[SSPXR-Requested-Changes.zip](https://github.com/ChrisAdderley/StationPartsExpansionRedux/files/2612379/SSPXR-Requested-Changes.zip)

**Comment by ChrisAdderley** [comment]
I'll look into it.

**Comment by ChrisAdderley** [comment]
Added for next version

**Comment by ChrisAdderley** [comment]
Released.
