### ISSUE TITLE
PTD-MULT Joint type 30° top node misaligned

### ISSUE THREAD

**Issue by HorusAK** [ChrisAdderley/StationPartsExpansionRedux#175]
Here're some images to explain:
https://imgur.com/yvwDF2p - You can see the part top node being a bi lower than the part top plane.
https://imgur.com/HbiAU5v - And this is the result of this misalignment.

**Comment by ChrisAdderley** [comment]
Should be addressed for next version

**Comment by ChrisAdderley** [comment]
Released.
