### ISSUE TITLE
PXL-1 internal and external hatches misalign

### ISSUE THREAD

**Issue by HorusAK** [ChrisAdderley/StationPartsExpansionRedux#176]
All images have the description:
View 1:
https://imgur.com/Q8HP2Al

View 2:
https://imgur.com/b7SAG2m

View 3:
https://imgur.com/xgieZqs

**Comment by ChrisAdderley** [comment]
Low priority fix, will look into it

**Comment by ChrisAdderley** [comment]
Investigated, not fixing, too much work. Would require a full rebuild of the centre section of the IVA
