### ISSUE TITLE
Inflatable modules don't allow kerbal inventory access

### ISSUE THREAD

**Issue by Teslamax** [ChrisAdderley/StationPartsExpansionRedux#177]
I have found that:
1. You are unable to access a kerbal's personal inventory while they're in an inflatable module. 
2. Kerbals inside such deployable parts have their personal inventory removed

I learned code contributed to "Tokamak Refurbished Parts" and "KIS" resolves said issue in that case:

[Tokamak Refurbished Parts commit](http://github.com/linuxgurugamer/Tokamak-Refurbished-Parts/commit/1bbb214ae86336d489c4e1fc2b7e9c6efaeb68e9)

Taniwha stated

> you need to either use Tokamak's PJHabitat.dll, or add the KIS support from it to whatever inflatable module you use
> (ie, the inflatable code needs to tell KIS to add the inventories)

**Comment by ChrisAdderley** [comment]
This should be fixed with the latest release
