### ISSUE TITLE
No Longer Compatible with USI-Life Support

### ISSUE THREAD

**Issue by LithoBrake** [ChrisAdderley/StationPartsExpansionRedux#181]
Kerbals are no longer happy in the station due to lost "Start Habitation" option of SPER parts after 1.6.x USI Update.

**Comment by ChrisAdderley** [comment]
Yes this is probably fixed in the PR I received recently. Would have been nice for RoverDude to notify major stakeholders before dropping this update.

**Comment by ChrisAdderley** [comment]
Released.
