### ISSUE TITLE
sspx-habitation-125-1 has no hatch 

### ISSUE THREAD

**Issue by CartierPierre** [ChrisAdderley/StationPartsExpansionRedux#185]
Hi,
Can you fix the bug with missions like "Save kerman in orbit of " wich is spawning into a sspx-habitation-125-1 module, without connector or any hatch to exit dans transfert crew member.
Thx

**Comment by ChrisAdderley** [comment]
Check the OP of the thread: 
https://forum.kerbalspaceprogram.com/index.php?/topic/170211-16x-stockalike-station-parts-redux-jan-17/

Specifically this section:
> Q: Kerbals for rescue contracts spawn in pods without airlocks! Unacceptable!
A: Download Shadowmage's Rescue Pod Validator.
