### ISSUE TITLE
PPD-8, PTD-8R, and the 'Vista' mods all break the sky when the sun is not occluded.

### ISSUE THREAD

**Issue by tymrek** [ChrisAdderley/StationPartsExpansionRedux#186]
Let me strart with I am running a heavily modded KSP. it's so modded I am including a CKAN mod list.: https://drive.google.com/open?id=1qyQsf-MU351WiEpsDlQyGyBh5eok6N6m

So far these three mods have been identified as mods that break my sky if I try to use them. This isn't game breaking, as I can still play and interact, it's just a visual bug. Anytime the sun is not occluded by some object/planet/moon, then the sky turns totally white.

**Comment by tymrek** [comment]
Further experimentation has established that this problem is associated  with the scatterer mod by blackrack.

**Comment by tymrek** [comment]
This issue is Linux-centric. I have recreated the entire build on a windows platform and the issue doesn't exist.

**Comment by ChrisAdderley** [comment]
Ah right. Doesn't seem like this is in my wheelhouse to fix then...
