### ISSUE TITLE
No flexible storage early in the tech tree

### ISSUE THREAD

**Issue by SteveBenz** [ChrisAdderley/StationPartsExpansionRedux#188]
[Progressive Colonization Systems](https://forum.kerbalspaceprogram.com/index.php?/topic/181852-15x~16x-progressivecolonizationsystem-life-support-colonization-for-more-fun-in-late-game/) is leveraging SSPX for storing things (including Kerbal food).  I got some feedback that it was hard to do multi-day missions early in the tech tree because there's no storage for it available.  Ultimately, I'd like to create a new part, based on B9, to store food, but in the short run, I've munged it with ModuleManager.  Still, seems to me like it'd be nice to have a storage can that's more accessible to the masses.

**Comment by ChrisAdderley** [comment]
I think you'd be better off taking the approach of cloning the part and making the changes there in the presence of your mod, it would be a cleaner solution than rearranging the SSPX tech tree, eg. 
`+PART[sspx-cargo-container-radial-small-1]`
