### ISSUE TITLE
Telescopic Clamp-O-Tron Model alignment issue.

### ISSUE THREAD

**Issue by omega489** [ChrisAdderley/StationPartsExpansionRedux#204]
The extendable pistons on the docking tube of the Telescopic Clamp-O-Tron are incorrectly aligned with the housing on the docking port.

https://media.discordapp.net/attachments/206472058228572162/603280793229590528/unknown.png?width=725&height=677

**Comment by ChrisAdderley** [comment]
Resolved for next version

**Comment by ChrisAdderley** [comment]
This should be fixed with the latest release
