### ISSUE TITLE
UV misalignment on PTD-1 crew tube

### ISSUE THREAD

**Issue by Maffif** [ChrisAdderley/StationPartsExpansionRedux#205]
Hidden by the insulated panel seams, it is barely apparent on the insulated version, but the metal version betrays it. Hard to be certain but I think there might also be a normal or AO bug on the window rim (seam is visible on the inside face of the outer rim of the shell, not the black inner rim)
edit: yes people use your shit we just don't want to bother you

**Comment by ChrisAdderley** [comment]
Resolved.
