### ISSUE TITLE
Action groups for auto-level and retract/extend

### ISSUE THREAD

**Issue by damonvv** [ChrisAdderley/StationPartsExpansionRedux#207]
As the title says,

I would like to see an option where you can use action groups to auto-level the legs for the terrain.
I would also like to see an option to extend/retract legs. I'm not sure if this is possible giving KSP 1.7 introduced a new functionality to the action group system. As long as it doesn't need the DLCs it would be sweet to have some sort of action group to extend/retract the leg. (No fully retracted or fully extended but a way to slowly extend and retract the leg). If this isn't possible then the auto-level action group is all we need!

**Comment by ChrisAdderley** [comment]
Auto-level implemented as an action group for next update. Trying to figure out how best to do the other requests.

**Comment by ChrisAdderley** [comment]
Done
