### ISSUE TITLE
Clamped foot orientation.

### ISSUE THREAD

**Issue by damonvv** [ChrisAdderley/StationPartsExpansionRedux#208]
All leg segments have its own orientation. While extended, the foot of the legs face the same orientation, not the one set originally.

**Comment by ChrisAdderley** [comment]
A `FeetPointOutwards` field has been added to `ModuleAdjustableLeg` for the next version. It forces the foot to point radially outward from the part centre along the green (y-up) axis.

**Comment by ChrisAdderley** [comment]
Done
