### ISSUE TITLE
Getting B9 Error

### ISSUE THREAD

**Issue by quade-ksp** [ChrisAdderley/StationPartsExpansionRedux#213]
B9PartSwitch = 2.12.1
KSP_VERSION = 1.8.1
StationPartsExpansionRedux = 1.3.1.0

Getting this error thrown up on main menu;
<img width="510" alt="Screen Shot 2019-12-14 at 10 07 58 PM" src="https://user-images.githubusercontent.com/35043614/70869084-045e2900-1f3c-11ea-97cb-49a5d4e09fdc.png">

**Comment by ChrisAdderley** [comment]
Going to need the actual log and a modlist - not getting this in a copy I just pulled down.

**Comment by quade-ksp** [comment]
Here ya go.

[Logs.zip](https://github.com/ChrisAdderley/StationPartsExpansionRedux/files/3976145/Logs.zip)

**Comment by ChrisAdderley** [comment]
That looks like it's just the Module Manager logfile, which is effectively empty - all it says is that it loaded things from cache.

I need the actual KSP logs (and perhaps the MM cache file). Looks like you're on OSX - I don't know offhand where the log file will be but I suspect you can find out with a google or two.

**Comment by quade-ksp** [comment]
So... these?

[KSP.log](https://github.com/ChrisAdderley/StationPartsExpansionRedux/files/3980231/KSP.log)

[ModuleManager.ConfigCache.zip](https://github.com/ChrisAdderley/StationPartsExpansionRedux/files/3980237/ModuleManager.ConfigCache.zip)

**Comment by ChrisAdderley** [comment]
Does the short 3.75m crew tube even show up ingame? There seems to be an error referenceing the model for that part. However there's no associated error with loading it...

I do see the Trails Agena docking port causing a critical error here. Not sure if that is problematic.
```
[LOG 09:10:27.708] Load(Model): TRAILSplus/Parts/Agena/DockingPortAgena
[EXC 09:10:27.710] EndOfStreamException: Unable to read beyond the end of the stream.
	System.IO.BinaryReader.FillBuffer (System.Int32 numBytes) (at <ad04dee02e7e4a85a1299c7ee81c79f6>:0)
	System.IO.BinaryReader.ReadInt32 () (at <ad04dee02e7e4a85a1299c7ee81c79f6>:0)
	PartReader.Read (UrlDir+UrlFile file) (at <394a98b9c7624adc895c04290da62640>:0)
	DatabaseLoaderModel_MU+<Load>d__1.MoveNext () (at <394a98b9c7624adc895c04290da62640>:0)
	UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <7d9ec060e791409ab3eb85c61e312ed6>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
	<LoadObjects>d__89:MoveNext()
	UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
```

**Comment by quade-ksp** [comment]
Hmmm...

![screenshot1](https://user-images.githubusercontent.com/35043614/71121924-4c778880-2194-11ea-9204-d8a699c902e2.png)

**Comment by ChrisAdderley** [comment]
Yep so something is causing the model not to load, which is strange - there seems to be no direct culprit in the log. 

I might suggest redownloading the mod to see if you have a corrupted file or similar. What source did you get it from? I'll take some time tomorrow to pull a copy from that source specifically to check.

**Comment by quade-ksp** [comment]
Downloaded directly from this Git.  It's possible it's conflicting with another mod.  I'll do some experimenting as well to try to see if it's conflicting with some other mod.

**Comment by ChrisAdderley** [comment]
I have to suspect a mod conflict, or perhaps a bad download or unzip. Have you tried redownloading the mod, deleting the current copy in GD, and reinstalling?

This evening I did the following tests: 
1) Pulling the master branch and moving the GameData to the right place for the mod and the optional patch
2) Downloading the release package from the Releases page and installing it as the readme directs

Neither of these resulted in any B9 errors, so I'm at a loss.

**Comment by quade-ksp** [comment]
I have some time this weekend blocked out to binary sort through the mods.  Hopefully I'll figure it out.  I'll let you know what I find out.

**Comment by quade-ksp** [comment]
Yep.  
Definitely Trails doing this.

**Comment by ChrisAdderley** [comment]
Going to close this one now as I think it is clear that all is ok from here.
