### ISSUE TITLE
Getting B9 Fatal Error

### ISSUE THREAD

**Issue by araige** [ChrisAdderley/StationPartsExpansionRedux#214]
B9PartSwitch = 2.12.1
KSP_VERSION = 1.8.1.2694(Linux)
StationPartsExpansionRedux = 1.3.1

Getting a Serious Warning and Fatal Error during PartLoader section of startup loading.
[KSP.log](https://github.com/ChrisAdderley/StationPartsExpansionRedux/files/4008682/KSP.log)

![Errors](https://user-images.githubusercontent.com/59346177/71563886-0a511f80-2a8f-11ea-82ea-6f70b561d83c.png)

I saw this on my heavily modded KSP after updating from this mod from 1.3.0(and a whole bunch of other mods and some new ones... smart right). Reverting to 1.3.0 fixed this issue. Then I tested 1.3.1 fresh download from spacedock alone on a Stock KSP that had never seen any mods and got the same Errors. I could close the warning but the quit on the fatal error window doesn't function.  Screenshots and Log file are from Stock.

**Comment by ChrisAdderley** [comment]
I need a logfile to actually investigate, but I don't see this in my game.
 
This type of error might indicate you are missing ModuleManager or something is interfering with it.

**Comment by araige** [comment]
I gave you my KSP.log it's right above the picture. Is there a different log you need? And was using the ModuleManager the is packaged with the mod

**Comment by ChrisAdderley** [comment]
Sorry my bad, perils of viewing from my phone. I'll have a look.

**Comment by ChrisAdderley** [comment]
Can you also post your ModuleManager.ConfigCache?
I don't see any major red flags but I can tell that something is interfering with B9PS loading the tank definition file. 
Worth check to make sure you have it. Look for SSPX/Patches/SSPXR-B9TankTypes.cfg

**Comment by araige** [comment]
Ok so something on my end must have screwed up downloading it because the SSPX/Patches folder was completely empty and it wasn't in the .zip either. I redownloaded it just now from spacedock and it was all there. What's really weird is that the only difference between this download content and the prev was the SSPX/Patches folder and the Extras/SSPXMetal folder were empty. Everything else was there. Installed this and it fixed my issues. Sorry to bother you.

**Comment by ChrisAdderley** [comment]
No problem! Great to see I didn't need to fix anything :P.
Spacedock downloads aren't always 100% reliable, I find. Could have been that.
