### ISSUE TITLE
1.25m cupola has low mass

### ISSUE THREAD

**Issue by LouisB3** [ChrisAdderley/StationPartsExpansionRedux#221]
The 1.25m cupola has a mass of only 0.09t, which is extremely low for a command pod. It's even less than the mass of the kerbal it can hold! This is probably a holdover from the old SSPX mod, when it was a structural/decorative part without crew capacity. 

To some extent, this is mitigated by the lack of certain critical amenities (like a hatch). However, cupolae have life-support functions in certain mods (KerbalHealth and USI-LS), and a part of such low mass is difficult to balance usefully in such cases. 

I would suggest that a mass of about 0.45t would be more consistent with half-diameter cupola, and that would be about consistent with other stock parts that hold a single kerbal as well. However, I'm not sure if this change would have any effect on existing craft.

**Comment by ChrisAdderley** [comment]
Thanks for noticing - will take a look.
