### ISSUE TITLE
Switchable tanks for Asylum radiation shelter

### ISSUE THREAD

**Issue by LouisB3** [ChrisAdderley/StationPartsExpansionRedux#222]
The description of the Asylum shelter module states that the radiation shielding comes from the radial tanks that are visible in the cross-sections of the module. (Neat!) Those tanks hold Monopropellant. 

KerbalHealth allows certain resources to provide radiation shielding (neat!), but Monopropellant is not among them. It would be great if the Asylum tanks were switchable to resources that granted shielding, such as water; this could be implemented in a similar way to the cargo containers, with auto-detection of installed mods. 

To be clear here, I'm volunteering to do this myself rather than requesting that somebody else implement the feature. But I do want to solicit design feedback so I don't don't submit something that's not consistent with the intention or "feel" of rest of the mod, or the preferences of its author.

There are a couple of ways this could work:

- Simplest solution would be to use the existing cargo container tank definitions, which would allow the storage of arbitrary resources. 
- But if we don't want just any resource to be storable in the asylum walls, could implement new tank definitions specific to this part, primarily for resources that function as rad-shielding. 
  - Monopropellant (existing)
  - Maybe other propellants, if this is deemed worthwhile (LFO, LH2, etc.)
  - Water
  - Lead
  - ~~Life support resources (Snacks or Supplies)~~ (actually this would probably make problems - this part would already have capacity added for these resources due to its crew capacity)

**Comment by Sharpspoonful** [comment]
Or change it to Ore. It would allow for a multipurpose use of the shelter, and would technically be more accurate.

**Comment by ChrisAdderley** [comment]
I couldn't sworn I replied to this already...

I like this idea generally, but let's limit this to a subset of fluids:
* MP
* LF/O, LF, O
* LH2, LH2/O
* Water
Nothing solid or bulk.

**Comment by ChrisAdderley** [comment]
I'd like to issue an update in the next few days in order to take advantage of B9PS's latest material changing abilities, is it reasonable to have this PR be part of it?

**Comment by LouisB3** [comment]
Yes! I was just working on this today and should be able to do some testing and submit a PR soon.

**Comment by ChrisAdderley** [comment]
PR is merged, will be in next version.
