### ISSUE TITLE
PPD Crew Tube

### ISSUE THREAD

**Issue by TrueMetis** [ChrisAdderley/StationPartsExpansionRedux#225]
Objects attached to the PPD series crew tubes appear to float above the tube. This effects the A1-3 and the radial attachment module. It does not seem to effect the smaller PTD series. I don't know if this is a limit caused by areas of the part being smaller than the attachment points, but haven't been able to find anything on this so thought I would post something.

**Comment by ChrisAdderley** [comment]
Yes, the parts are approximated by a collision cylinder which is the size of the base for performance reasons. To perfectly accurately model the surface, i would need to approximately quadruple the physics 'impact' of the part, which I don't think is worth it.

**Comment by TrueMetis** [comment]
That is very fair, thanks for the answer.
