### ISSUE TITLE
Realism Overhaul Config File

### ISSUE THREAD

**Issue by KevinClaytonGustafson** [ChrisAdderley/StationPartsExpansionRedux#229]
I wanted to use these in RO but realized there wasn't a cfg file. I've made a basic one that just turns on RO for all the parts. I will work more to refine it and make it more RO friendly.

[GameData.zip](https://github.com/ChrisAdderley/StationPartsExpansionRedux/files/4500593/GameData.zip)

**Comment by ChrisAdderley** [comment]
RO configs should be place in the RO mod, not the compatible mods.
