### ISSUE TITLE
Some parts have no way to exit

### ISSUE THREAD

**Issue by pandrien** [ChrisAdderley/StationPartsExpansionRedux#230]
Some of the parts have no way for Kerbals to exit. This is mainly an issue when contracts trap a Kerbal in one of these parts for a rescue contract: 
- Sunrise
- Star
- Porthole

Is this actually an intended design feature? Even stock parts like the MK1 Crew Cabin have an exit hatch.

Edit. I'm running version 1.3.4 on KSP 1.9.1 installed via CKAN

**Comment by ChrisAdderley** [comment]
Yes, this is intended. I suggest installing RescuePodValidator that stops Kerbals from spawning in pods without hatches.
