### ISSUE TITLE
[Feature Request] - Colorable Cargo Containers

### ISSUE THREAD

**Issue by RobMayer** [ChrisAdderley/StationPartsExpansionRedux#239]
Title says it all: It'd be wonderful if we could change the color of the cargo containers using a switch - I tried making a MM patch, but without knowing the naming convention of your cargo container's transforms, I can't do it myself.

**Comment by ChrisAdderley** [comment]
I don't intend to do this, but if you want to look at the naming conventions it is quite easy. Use a tool like [DebugStuff](https://forum.kerbalspaceprogram.com/index.php?/topic/135726-18-debugstuff-2020-06-29-see-the-hidden-secrets-of-the-game-objects/) . It allow you to inspect the hierarchies of models ingame.
