### ISSUE TITLE
PPD-AR Pressurized Radial Attachment Module - Missing Top Node

### ISSUE THREAD

**Issue by Poodmund** [ChrisAdderley/StationPartsExpansionRedux#243]
Part Name: sspx-attach-25-1

```
	// --- node definitions ---
	node_stack_top = 0.0, 0.586, 0.0, 0.0, 1.0, 0.0, 2
	node_attach = 0.0, 0.048, 0.0, 0.0, -1.0, 0.0, 2
```
These are the attachment node points in the config but as you can see in the screenshot, the top node doesn't appear in the editor.

![Untitled-1](https://user-images.githubusercontent.com/10106634/98450339-ef7e1b80-2133-11eb-9d6f-dcee678030ff.png)

I think the nodes needs to be the following:
```
	// --- node definitions ---
	node_stack_top = 0.0, 0.586, 0.0, 0.0, 1.0, 0.0, 2
	node_stack_bottom = 0.0, -0.580, 0.0, 0.0, -1.0, 0.0, 2
```
![Untitled-1](https://user-images.githubusercontent.com/10106634/98451119-d331ad00-213a-11eb-9b06-0fba8834ed78.png)

**Comment by ChrisAdderley** [comment]
Nope, that seems as intended. It's like the radial attach points.

**Comment by Poodmund** [comment]
I'm dumb.
