### ISSUE TITLE
PTD-TRUSS-S Storage Module has invisible walls

### ISSUE THREAD

**Issue by marcusirgens** [ChrisAdderley/StationPartsExpansionRedux#97]
Hi, wanted to preface this by saying that after having played around with this mod for a couple of hours, I love it. Fantastic upgrade from the last SSPX.

I'm opening issues for the bugs that I find. :)

The PTD-TRUSS-S has invisible walls on the top and bottom, also in the doors, making it impossible to select items inside or fly into it during EVAs without moving the camera inside the container.

**Comment by ChrisAdderley** [comment]
Thanks!

Should be resolved, for larger container also.
